# generate-lucide-icons.ps1
#
# Convert vendor/lucide-icons-*/icons/*.svg to PNG and emit a Zig source
# file inside the framework module so @embedFile can reach the PNGs.
#
# Each constant is named after the SVG basename (hyphens -> underscores;
# digit-leading names get an `_` prefix).
#
# Usage:
#   pwsh scripts/generate-lucide-icons.ps1                # render + emit zig
#   pwsh scripts/generate-lucide-icons.ps1 -SkipRender    # re-emit zig only
#   pwsh scripts/generate-lucide-icons.ps1 -Size 128      # different size

param(
    [string]$ResvgPath = $null,
    [string]$SvgDir    = $null,
    [int]   $Size      = 64,
    [switch]$SkipRender
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot

# Auto-detect lucide-icons-* directory under vendor/ if not specified.
if (-not $SvgDir) {
    $candidates = Get-ChildItem -Path (Join-Path $repoRoot "vendor") -Directory -Filter "lucide-icons-*"
    if ($candidates.Count -eq 0) {
        Write-Error "No vendor/lucide-icons-* directory found."
        exit 1
    }
    $SvgDir = Join-Path $candidates[0].FullName "icons"
}

if (-not $ResvgPath) {
    $ResvgPath = Join-Path $repoRoot "vendor\resvg-win64\resvg.exe"
}

$outDir = Join-Path $repoRoot "framework\src\lucide"
$pngDir = Join-Path $outDir   "png"

if (-not (Test-Path $SvgDir)) {
    Write-Error "lucide source not found at $SvgDir."
    exit 1
}

if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
if (-not (Test-Path $pngDir)) { New-Item -ItemType Directory -Path $pngDir -Force | Out-Null }

# ── render ─────────────────────────────────────────────────────────────
if (-not $SkipRender) {
    if (-not (Test-Path $ResvgPath)) {
        Write-Error "resvg.exe not found at $ResvgPath."
        exit 1
    }

    $svgFiles = Get-ChildItem -Path $SvgDir -Filter "*.svg"
    $total = $svgFiles.Count
    Write-Host "Rendering $total SVG -> PNG ($Size x $Size)..."

    $done = 0
    foreach ($svg in $svgFiles) {
        $pngPath = Join-Path $pngDir "$($svg.BaseName).png"
        & $ResvgPath --width $Size --height $Size $svg.FullName $pngPath 2>$null 1>$null
        $done++
        if (($done % 100) -eq 0) {
            Write-Host ("  ... {0} / {1}" -f $done, $total)
        }
    }
    Write-Host "Done rendering: $done files"
} else {
    Write-Host "Skipping render (re-using existing PNGs)."
}

# ── emit Zig source ────────────────────────────────────────────────────
Write-Host "Generating icons.zig..."
$pngFiles = Get-ChildItem -Path $pngDir -Filter "*.png" | Sort-Object Name

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// AUTO-GENERATED by scripts/generate-lucide-icons.ps1 - do not edit by hand.")
[void]$sb.AppendLine("// Source: lucide icons (ISC license). See LICENSE.txt in this directory.")
[void]$sb.AppendLine("// Each variant maps to the raw PNG bytes at $Size x $Size. Decode via")
[void]$sb.AppendLine("//   awt.Image.fromMemory(allocator, device, lucide.Icon.save.bytes())")
[void]$sb.AppendLine("// or use Application.icon(.save) to get a cached, GPU-uploaded Image.")
[void]$sb.AppendLine("")

# Zig reserved words / built-in type names that need @"..." escaping
# when used as identifiers. Keywords plus the common primitive type names
# that conflict (`type` is the main one that hits lucide).
$zigKeywords = @(
    'align','allowzero','and','anyframe','anytype','asm','async','await','break',
    'callconv','catch','comptime','const','continue','defer','else','enum','errdefer',
    'error','export','extern','false','fn','for','if','inline','linksection','noalias',
    'noinline','nosuspend','null','opaque','or','orelse','packed','pub','resume',
    'return','struct','suspend','switch','test','threadlocal','true','try','undefined',
    'union','unreachable','usingnamespace','var','volatile','while',
    # primitive types (cannot be used as const identifiers without @"...")
    'type','void','bool','noreturn','anyopaque','anyerror',
    'comptime_int','comptime_float','isize','usize',
    'f16','f32','f64','f80','f128',
    'c_short','c_ushort','c_int','c_uint','c_long','c_ulong',
    'c_longlong','c_ulonglong','c_longdouble','c_char'
)

# Pre-compute (ident, png-name) pairs.
$entries = foreach ($png in $pngFiles) {
    $name  = $png.BaseName
    $ident = $name -replace '-', '_'
    if ($ident -match '^[0-9]') { $ident = "_" + $ident }
    if ($zigKeywords -contains $ident) { $ident = '@"' + $ident + '"' }
    [pscustomobject]@{ Ident = $ident; PngName = $png.Name }
}

# Emit the Icon enum.
[void]$sb.AppendLine("pub const Icon = enum {")
foreach ($e in $entries) {
    [void]$sb.AppendLine("    " + $e.Ident + ",")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    pub const count = @typeInfo(Icon).@" + '"' + "enum" + '"' + ".fields.len;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    pub fn bytes(self: Icon) []const u8 {")
[void]$sb.AppendLine("        return all_bytes[@intFromEnum(self)];")
[void]$sb.AppendLine("    }")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")

# Emit the lookup table. Indexed by @intFromEnum(Icon), so the ordering must
# match the enum body above. The whole table ends up in every binary that
# calls Icon.bytes() (the runtime indirection blocks per-variant dead-code
# elimination, even with a switch-of-@embedFile alternative); see
# `framework/doc/application.md` "icon_cache" for the size discussion.
[void]$sb.AppendLine("const all_bytes = [_][]const u8{")
foreach ($e in $entries) {
    [void]$sb.AppendLine('    @embedFile("png/' + $e.PngName + '"),')
}
[void]$sb.AppendLine("};")

$zigPath = Join-Path $outDir "icons.zig"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($zigPath, $sb.ToString(), $utf8NoBom)
Write-Host ("Wrote: {0} ({1} entries)" -f $zigPath, $pngFiles.Count)

# ── copy LICENSE ───────────────────────────────────────────────────────
# LICENSE sits one level above the icons/ directory (vendor/lucide-icons-*/LICENSE.txt).
$licenseSrc = Join-Path (Split-Path -Parent $SvgDir) "LICENSE.txt"
$licenseDst = Join-Path $outDir "LICENSE.txt"
if (Test-Path $licenseSrc) {
    Copy-Item $licenseSrc $licenseDst -Force
    Write-Host "Copied LICENSE.txt -> $licenseDst"
} else {
    Write-Warning "No LICENSE.txt found at $licenseSrc"
}

Write-Host "All done."
